import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header/Header";
import QueryProvider from "./QueryProvider";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body className={`${openSans.variable}`}>
          <Header />
          {children}
        </body>
      </html>
    </QueryProvider>
  );
}
